language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-node-capitaljs' ]; then cd .. && eval "mv $currentfolder generator-node-capitaljs" && cd generator-node-capitaljs; fi

